// AUTO-GENERIERT von scripts/normtext/bund-stubs-generieren.ts — NICHT von Hand editieren.
// Verifizierte «nur-live-link»-Stubs wichtiger Bundesgesetze (Titel/ELI/Stand aus
// Fedlex-SPARQL, §7). Regenerieren: npm run normtext:bund-stubs -- --datum=$(date +%F)
import type { ErlassRegistereintrag } from './register';

export const BUND_STUBS: ErlassRegistereintrag[] = [
  { key: 'AIG', ebene: 'bund', kuerzel: 'AIG', titel: 'Bundesgesetz vom 16. Dezember 2005 über die Ausländerinnen und Ausländer und über die Integration (Ausländer- und Integrationsgesetz, AIG)', sr: '142.20', rechtsgebiet: 'oeffentlich', sprache: 'de', rang: 90, status: 'nur-live-link', quelleUrl: 'https://www.fedlex.admin.ch/eli/cc/2007/758/de', stand: '2026-06-12' },
  { key: 'ASYLG', ebene: 'bund', kuerzel: 'AsylG', titel: 'Asylgesetz vom 26. Juni 1998 (AsylG)', sr: '142.31', rechtsgebiet: 'oeffentlich', sprache: 'de', rang: 90, status: 'nur-live-link', quelleUrl: 'https://www.fedlex.admin.ch/eli/cc/1999/358/de', stand: '2026-06-12' },
  { key: 'GLG', ebene: 'bund', kuerzel: 'GlG', titel: 'Bundesgesetz vom 24. März 1995 über die Gleichstellung von Frau und Mann (Gleichstellungsgesetz, GlG)', sr: '151.1', rechtsgebiet: 'oeffentlich', sprache: 'de', rang: 90, status: 'nur-live-link', quelleUrl: 'https://www.fedlex.admin.ch/eli/cc/1996/1498_1498_1498/de', stand: '2020-07-01' },
  { key: 'PARTG', ebene: 'bund', kuerzel: 'PartG', titel: 'Bundesgesetz vom 18. Juni 2004 über die eingetragene Partnerschaft gleichgeschlechtlicher Paare (Partnerschaftsgesetz, PartG)', sr: '211.231', rechtsgebiet: 'privat', sprache: 'de', rang: 90, status: 'nur-live-link', quelleUrl: 'https://www.fedlex.admin.ch/eli/cc/2005/782/de', stand: '2025-01-01' },
  { key: 'BGBB', ebene: 'bund', kuerzel: 'BGBB', titel: 'Bundesgesetz vom 4. Oktober 1991 über das bäuerliche Bodenrecht (BGBB)', sr: '211.412.11', rechtsgebiet: 'privat', sprache: 'de', rang: 90, status: 'nur-live-link', quelleUrl: 'https://www.fedlex.admin.ch/eli/cc/1993/1410_1410_1410/de', stand: '2014-01-01' },
  { key: 'JSTG', ebene: 'bund', kuerzel: 'JStG', titel: 'Bundesgesetz vom 20. Juni 2003 über das Jugendstrafrecht (Jugendstrafgesetz, JStG)', sr: '311.1', rechtsgebiet: 'straf', sprache: 'de', rang: 90, status: 'nur-live-link', quelleUrl: 'https://www.fedlex.admin.ch/eli/cc/2006/551/de', stand: '2025-07-01' },
  { key: 'STHG', ebene: 'bund', kuerzel: 'StHG', titel: 'Bundesgesetz vom 14. Dezember 1990 über die Harmonisierung der direkten Steuern der Kantone und Gemeinden (Steuerharmonisierungsgesetz, StHG)', sr: '642.14', rechtsgebiet: 'sozial-abgaben', sprache: 'de', rang: 90, status: 'nur-live-link', quelleUrl: 'https://www.fedlex.admin.ch/eli/cc/1991/1256_1256_1256/de', stand: '2025-01-01' },
  { key: 'AHVG', ebene: 'bund', kuerzel: 'AHVG', titel: 'Bundesgesetz vom 20. Dezember 1946 über die Alters- und Hinterlassenenversicherung (AHVG)', sr: '831.10', rechtsgebiet: 'sozial-abgaben', sprache: 'de', rang: 90, status: 'nur-live-link', quelleUrl: 'https://www.fedlex.admin.ch/eli/cc/63/837_843_843/de', stand: '2026-01-01' },
  { key: 'IVG', ebene: 'bund', kuerzel: 'IVG', titel: 'Bundesgesetz vom 19. Juni 1959 über die Invalidenversicherung (IVG)', sr: '831.20', rechtsgebiet: 'sozial-abgaben', sprache: 'de', rang: 90, status: 'nur-live-link', quelleUrl: 'https://www.fedlex.admin.ch/eli/cc/1959/827_857_845/de', stand: '2026-01-01' },
  { key: 'BVG', ebene: 'bund', kuerzel: 'BVG', titel: 'Bundesgesetz vom 25. Juni 1982 über die berufliche Alters-, Hinterlassenen- und Invalidenvorsorge (BVG)', sr: '831.40', rechtsgebiet: 'sozial-abgaben', sprache: 'de', rang: 90, status: 'nur-live-link', quelleUrl: 'https://www.fedlex.admin.ch/eli/cc/1983/797_797_797/de', stand: '2025-01-01' },
  { key: 'UVG', ebene: 'bund', kuerzel: 'UVG', titel: 'Bundesgesetz vom 20. März 1981 über die Unfallversicherung (UVG)', sr: '832.20', rechtsgebiet: 'sozial-abgaben', sprache: 'de', rang: 90, status: 'nur-live-link', quelleUrl: 'https://www.fedlex.admin.ch/eli/cc/1982/1676_1676_1676/de', stand: '2026-01-01' },
  { key: 'AVIG', ebene: 'bund', kuerzel: 'AVIG', titel: 'Bundesgesetz vom 25. Juni 1982 über die obligatorische Arbeitslosenversicherung und die Insolvenzentschädigung (Arbeitslosenversicherungsgesetz, AVIG)', sr: '837.0', rechtsgebiet: 'sozial-abgaben', sprache: 'de', rang: 90, status: 'nur-live-link', quelleUrl: 'https://www.fedlex.admin.ch/eli/cc/1982/2184_2184_2184/de', stand: '2026-01-01' },
  { key: 'RPG', ebene: 'bund', kuerzel: 'RPG', titel: 'Bundesgesetz vom 22. Juni 1979 über die Raumplanung (Raumplanungsgesetz, RPG)', sr: '700', rechtsgebiet: 'oeffentlich', sprache: 'de', rang: 90, status: 'nur-live-link', quelleUrl: 'https://www.fedlex.admin.ch/eli/cc/1979/1573_1573_1573/de', stand: '2026-04-01' },
  { key: 'USG', ebene: 'bund', kuerzel: 'USG', titel: 'Bundesgesetz vom 7. Oktober 1983 über den Umweltschutz (Umweltschutzgesetz, USG)', sr: '814.01', rechtsgebiet: 'oeffentlich', sprache: 'de', rang: 90, status: 'nur-live-link', quelleUrl: 'https://www.fedlex.admin.ch/eli/cc/1984/1122_1122_1122/de', stand: '2026-04-01' },
  { key: 'GSCHG', ebene: 'bund', kuerzel: 'GSchG', titel: 'Bundesgesetz vom 24. Januar 1991 über den Schutz der Gewässer (Gewässerschutzgesetz, GSchG)', sr: '814.20', rechtsgebiet: 'oeffentlich', sprache: 'de', rang: 90, status: 'nur-live-link', quelleUrl: 'https://www.fedlex.admin.ch/eli/cc/1992/1860_1860_1860/de', stand: '2025-08-01' },
  { key: 'NHG', ebene: 'bund', kuerzel: 'NHG', titel: 'Bundesgesetz vom 1. Juli 1966 über den Natur- und Heimatschutz (NHG)', sr: '451', rechtsgebiet: 'oeffentlich', sprache: 'de', rang: 90, status: 'nur-live-link', quelleUrl: 'https://www.fedlex.admin.ch/eli/cc/1966/1637_1694_1679/de', stand: '2025-08-01' },
  { key: 'BGFA', ebene: 'bund', kuerzel: 'BGFA', titel: 'Bundesgesetz vom 23. Juni 2000 über die Freizügigkeit der Anwältinnen und Anwälte (Anwaltsgesetz, BGFA)', sr: '935.61', rechtsgebiet: 'prozess', sprache: 'de', rang: 90, status: 'nur-live-link', quelleUrl: 'https://www.fedlex.admin.ch/eli/cc/2002/153/de', stand: '2025-07-01' },
  { key: 'GWG', ebene: 'bund', kuerzel: 'GwG', titel: 'Bundesgesetz vom 10. Oktober 1997 über die Bekämpfung der Geldwäscherei und der Terrorismusfinanzierung (Geldwäschereigesetz, GwG)', sr: '955.0', rechtsgebiet: 'oeffentlich', sprache: 'de', rang: 90, status: 'nur-live-link', quelleUrl: 'https://www.fedlex.admin.ch/eli/cc/1998/892_892_892/de', stand: '2024-03-01' },
  { key: 'BANKG', ebene: 'bund', kuerzel: 'BankG', titel: 'Bundesgesetz vom 8. November 1934 über die Banken und Sparkassen (Bankengesetz, BankG)', sr: '952.0', rechtsgebiet: 'oeffentlich', sprache: 'de', rang: 90, status: 'nur-live-link', quelleUrl: 'https://www.fedlex.admin.ch/eli/cc/51/117_121_129/de', stand: '2024-01-01' },
  { key: 'KAG', ebene: 'bund', kuerzel: 'KAG', titel: 'Bundesgesetz vom 23. Juni 2006 über die kollektiven Kapitalanlagen (Kollektivanlagengesetz, KAG)', sr: '951.31', rechtsgebiet: 'oeffentlich', sprache: 'de', rang: 90, status: 'nur-live-link', quelleUrl: 'https://www.fedlex.admin.ch/eli/cc/2006/822/de', stand: '2024-03-01' },
  { key: 'MG', ebene: 'bund', kuerzel: 'MG', titel: 'Bundesgesetz vom 3. Februar 1995 über die Armee und die Militärverwaltung (Militärgesetz, MG)', sr: '510.10', rechtsgebiet: 'oeffentlich', sprache: 'de', rang: 90, status: 'nur-live-link', quelleUrl: 'https://www.fedlex.admin.ch/eli/cc/1995/4093_4093_4093/de', stand: '2026-06-01' },
  { key: 'EMRK', ebene: 'bund', kuerzel: 'EMRK', titel: 'Konvention vom 4. November 1950 zum Schutze der Menschenrechte und Grundfreiheiten (EMRK)', sr: '0.101', rechtsgebiet: 'oeffentlich', sprache: 'de', rang: 90, status: 'nur-live-link', quelleUrl: 'https://www.fedlex.admin.ch/eli/cc/1974/2151_2151_2151/de', stand: '2022-09-16' },
];
