// AUTO-GENERIERT von scripts/normtext/bund-stubs-generieren.ts — NICHT von Hand editieren.
// Verifizierte «nur-live-link»-Stubs wichtiger Bundesgesetze (Titel/ELI/Stand aus
// Fedlex-SPARQL, §7). Regenerieren: npm run normtext:bund-stubs -- --datum=$(date +%F)
import type { ErlassRegistereintrag } from './register';

export const BUND_STUBS: ErlassRegistereintrag[] = [
  { key: 'PRHG', ebene: 'bund', kuerzel: 'PrHG', titel: 'Bundesgesetz vom 18. Juni 1993 über die Produktehaftpflicht (Produktehaftpflichtgesetz, PrHG)', sr: '221.112.944', rechtsgebiet: 'privat', sprache: 'de', rang: 90, status: 'nur-live-link', quelleUrl: 'https://www.fedlex.admin.ch/eli/cc/1993/3122_3122_3122/de', stand: '2010-07-01' },
  { key: 'EMRK', ebene: 'bund', kuerzel: 'EMRK', titel: 'Konvention vom 4. November 1950 zum Schutze der Menschenrechte und Grundfreiheiten (EMRK)', sr: '0.101', rechtsgebiet: 'international', sprache: 'de', rang: 90, status: 'nur-live-link', quelleUrl: 'https://www.fedlex.admin.ch/eli/cc/1974/2151_2151_2151/de', stand: '2022-09-16' },
  { key: 'CISG', ebene: 'bund', kuerzel: 'CISG', titel: 'Übereinkommen der Vereinten Nationen vom 11. April 1980 über Verträge über den internationalen Warenkauf', sr: '0.221.211.1', rechtsgebiet: 'international', sprache: 'de', rang: 90, status: 'nur-live-link', quelleUrl: 'https://www.fedlex.admin.ch/eli/cc/1991/307_307_307/de', stand: '2026-05-22' },
  { key: 'LUGUE', ebene: 'bund', kuerzel: 'LugÜ', titel: 'Übereinkommen vom 30. Oktober 2007 über die gerichtliche Zuständigkeit und die Anerkennung und Vollstreckung von Entscheidungen in Zivil- und Handelssachen (Lugano-Übereinkommen, LugÜ) (mit Prot. und Anhängen)', sr: '0.275.12', rechtsgebiet: 'international', sprache: 'de', rang: 90, status: 'nur-live-link', quelleUrl: 'https://www.fedlex.admin.ch/eli/cc/2010/801/de', stand: '2016-04-08' },
  { key: 'HZUE', ebene: 'bund', kuerzel: 'HZÜ', titel: 'Übereinkommen vom 15. November 1965 über die Zustellung gerichtlicher und aussergerichtlicher Schriftstücke im Ausland in Zivil- oder Handelssachen (mit Anhang)', sr: '0.274.131', rechtsgebiet: 'international', sprache: 'de', rang: 90, status: 'nur-live-link', quelleUrl: 'https://www.fedlex.admin.ch/eli/cc/1994/2809_2809_2809/de', stand: '2023-06-12' },
  { key: 'HBEWUE', ebene: 'bund', kuerzel: 'HBewÜ', titel: 'Übereinkommen vom 18. März 1970 über die Beweisaufnahme im Ausland in Zivil- oder Handelssachen', sr: '0.274.132', rechtsgebiet: 'international', sprache: 'de', rang: 90, status: 'nur-live-link', quelleUrl: 'https://www.fedlex.admin.ch/eli/cc/1994/2824_2824_2824/de', stand: '2026-01-01' },
  { key: 'HKUE', ebene: 'bund', kuerzel: 'HKÜ', titel: 'Übereinkommen vom 25. Oktober 1980 über die zivilrechtlichen Aspekte internationaler Kindesentführung (mit Beilage und Verzeichnis)', sr: '0.211.230.02', rechtsgebiet: 'international', sprache: 'de', rang: 90, status: 'nur-live-link', quelleUrl: 'https://www.fedlex.admin.ch/eli/cc/1983/1694_1694_1694/de', stand: '2024-06-13' },
  { key: 'FZA', ebene: 'bund', kuerzel: 'FZA', titel: 'Abkommen vom 21. Juni 1999 zwischen der Schweizerischen Eidgenossenschaft einerseits und der Europäischen Gemeinschaft und ihren Mitgliedstaaten andererseits über die Freizügigkeit (mit Anhängen, Prot. und Schlussakte)', sr: '0.142.112.681', rechtsgebiet: 'international', sprache: 'de', rang: 90, status: 'nur-live-link', quelleUrl: 'https://www.fedlex.admin.ch/eli/cc/2002/243/de', stand: '2020-12-15' },
  { key: 'VRK', ebene: 'bund', kuerzel: 'VRK', titel: 'Wiener Übereinkommen vom 23. Mai 1969 über das Recht der Verträge (mit Anhang)', sr: '0.111', rechtsgebiet: 'international', sprache: 'de', rang: 90, status: 'nur-live-link', quelleUrl: 'https://www.fedlex.admin.ch/eli/cc/1990/1112_1112_1112/de', stand: '2020-05-08' },
  { key: 'UNO_PAKT_II', ebene: 'bund', kuerzel: 'UNO-Pakt II', titel: 'Internationaler Pakt vom 16. Dezember 1966 über bürgerliche und politische Rechte', sr: '0.103.2', rechtsgebiet: 'international', sprache: 'de', rang: 90, status: 'nur-live-link', quelleUrl: 'https://www.fedlex.admin.ch/eli/cc/1993/750_750_750/de', stand: '2022-05-09' },
];
