// AUTO-GENERIERT von scripts/normtext/bund-stubs-generieren.ts — NICHT von Hand editieren.
// Verifizierte «nur-live-link»-Stubs wichtiger Bundesgesetze (Titel/ELI/Stand aus
// Fedlex-SPARQL, §7). Regenerieren: npm run normtext:bund-stubs -- --datum=$(date +%F)
import type { ErlassRegistereintrag } from './register';

export const BUND_STUBS: ErlassRegistereintrag[] = [
  { key: 'SORTG', ebene: 'bund', kuerzel: 'SortG', titel: 'Bundesgesetz vom 20. März 1975 über den Schutz von Pflanzenzüchtungen (Sortenschutzgesetz)', sr: '232.16', rechtsgebiet: 'privat', sprache: 'de', rang: 90, status: 'nur-live-link', quelleUrl: 'https://www.fedlex.admin.ch/eli/cc/1977/862_862_862/de', stand: '2011-01-01' },
  { key: 'PRHG', ebene: 'bund', kuerzel: 'PrHG', titel: 'Bundesgesetz vom 18. Juni 1993 über die Produktehaftpflicht (Produktehaftpflichtgesetz, PrHG)', sr: '221.112.944', rechtsgebiet: 'privat', sprache: 'de', rang: 90, status: 'nur-live-link', quelleUrl: 'https://www.fedlex.admin.ch/eli/cc/1993/3122_3122_3122/de', stand: '2010-07-01' },
  { key: 'PRG', ebene: 'bund', kuerzel: 'PRG', titel: 'Bundesgesetz vom 18. Juni 1993 über Pauschalreisen', sr: '944.3', rechtsgebiet: 'privat', sprache: 'de', rang: 90, status: 'nur-live-link', quelleUrl: 'https://www.fedlex.admin.ch/eli/cc/1993/3152_3152_3152/de', stand: '2021-08-20' },
  { key: 'BEG', ebene: 'bund', kuerzel: 'BEG', titel: 'Bundesgesetz vom 3. Oktober 2008 über Bucheffekten (Bucheffektengesetz, BEG)', sr: '957.1', rechtsgebiet: 'privat', sprache: 'de', rang: 90, status: 'nur-live-link', quelleUrl: 'https://www.fedlex.admin.ch/eli/cc/2009/450/de', stand: '2023-01-01' },
  { key: 'MSTG', ebene: 'bund', kuerzel: 'MStG', titel: 'Militärstrafgesetz vom 13. Juni 1927 (MStG)', sr: '321.0', rechtsgebiet: 'straf', sprache: 'de', rang: 90, status: 'nur-live-link', quelleUrl: 'https://www.fedlex.admin.ch/eli/cc/43/359_375_369/de', stand: '2026-06-08' },
  { key: 'MSTP', ebene: 'bund', kuerzel: 'MStP', titel: 'Militärstrafprozess vom 23. März 1979 (MStP)', sr: '322.1', rechtsgebiet: 'straf', sprache: 'de', rang: 90, status: 'nur-live-link', quelleUrl: 'https://www.fedlex.admin.ch/eli/cc/1979/1059_1059_1059/de', stand: '2024-07-01' },
  { key: 'IRSG', ebene: 'bund', kuerzel: 'IRSG', titel: 'Bundesgesetz vom 20. März 1981 über internationale Rechtshilfe in Strafsachen (Rechtshilfegesetz, IRSG)', sr: '351.1', rechtsgebiet: 'straf', sprache: 'de', rang: 90, status: 'nur-live-link', quelleUrl: 'https://www.fedlex.admin.ch/eli/cc/1982/846_846_846/de', stand: '2024-01-01' },
  { key: 'MVG', ebene: 'bund', kuerzel: 'MVG', titel: 'Bundesgesetz vom 19. Juni 1992 über die Militärversicherung (MVG)', sr: '833.1', rechtsgebiet: 'sozial-abgaben', sprache: 'de', rang: 90, status: 'nur-live-link', quelleUrl: 'https://www.fedlex.admin.ch/eli/cc/1993/3043_3043_3043/de', stand: '2024-01-01' },
  { key: 'ENG', ebene: 'bund', kuerzel: 'EnG', titel: 'Energiegesetz vom 30. September 2016 (EnG)', sr: '730.0', rechtsgebiet: 'oeffentlich', sprache: 'de', rang: 90, status: 'nur-live-link', quelleUrl: 'https://www.fedlex.admin.ch/eli/cc/2017/762/de', stand: '2026-04-01' },
  { key: 'CO2_GESETZ', ebene: 'bund', kuerzel: 'CO2-Gesetz', titel: 'Bundesgesetz vom 23. Dezember 2011 über die Reduktion der CO2-Emissionen (CO2-Gesetz)', sr: '641.71', rechtsgebiet: 'oeffentlich', sprache: 'de', rang: 90, status: 'nur-live-link', quelleUrl: 'https://www.fedlex.admin.ch/eli/cc/2012/855/de', stand: '2025-01-01' },
  { key: 'EPG', ebene: 'bund', kuerzel: 'EpG', titel: 'Bundesgesetz vom 28. September 2012 über die Bekämpfung übertragbarer Krankheiten des Menschen (Epidemiengesetz, EpG)', sr: '818.101', rechtsgebiet: 'oeffentlich', sprache: 'de', rang: 90, status: 'nur-live-link', quelleUrl: 'https://www.fedlex.admin.ch/eli/cc/2015/297/de', stand: '2025-08-01' },
  { key: 'TXG', ebene: 'bund', kuerzel: 'TxG', titel: 'Bundesgesetz vom 8. Oktober 2004 über die Transplantation von Organen, Geweben und Zellen (Transplantationsgesetz)', sr: '810.21', rechtsgebiet: 'oeffentlich', sprache: 'de', rang: 90, status: 'nur-live-link', quelleUrl: 'https://www.fedlex.admin.ch/eli/cc/2007/279/de', stand: '2021-02-01' },
  { key: 'LMG', ebene: 'bund', kuerzel: 'LMG', titel: 'Bundesgesetz vom 20. Juni 2014 über Lebensmittel und Gebrauchsgegenstände (Lebensmittelgesetz, LMG)', sr: '817.0', rechtsgebiet: 'oeffentlich', sprache: 'de', rang: 90, status: 'nur-live-link', quelleUrl: 'https://www.fedlex.admin.ch/eli/cc/2017/62/de', stand: '2024-10-01' },
  { key: 'LFG', ebene: 'bund', kuerzel: 'LFG', titel: 'Bundesgesetz vom 21. Dezember 1948 über die Luftfahrt (Luftfahrtgesetz, LFG)', sr: '748.0', rechtsgebiet: 'oeffentlich', sprache: 'de', rang: 90, status: 'nur-live-link', quelleUrl: 'https://www.fedlex.admin.ch/eli/cc/1950/471_491_479/de', stand: '2026-01-01' },
  { key: 'EBG', ebene: 'bund', kuerzel: 'EBG', titel: 'Eisenbahngesetz vom 20. Dezember 1957 (EBG)', sr: '742.101', rechtsgebiet: 'oeffentlich', sprache: 'de', rang: 90, status: 'nur-live-link', quelleUrl: 'https://www.fedlex.admin.ch/eli/cc/1958/335_341_347/de', stand: '2026-01-01' },
  { key: 'FMG', ebene: 'bund', kuerzel: 'FMG', titel: 'Fernmeldegesetz vom 30. April 1997 (FMG)', sr: '784.10', rechtsgebiet: 'oeffentlich', sprache: 'de', rang: 90, status: 'nur-live-link', quelleUrl: 'https://www.fedlex.admin.ch/eli/cc/1997/2187_2187_2187/de', stand: '2026-06-01' },
  { key: 'MG', ebene: 'bund', kuerzel: 'MG', titel: 'Bundesgesetz vom 3. Februar 1995 über die Armee und die Militärverwaltung (Militärgesetz, MG)', sr: '510.10', rechtsgebiet: 'oeffentlich', sprache: 'de', rang: 90, status: 'nur-live-link', quelleUrl: 'https://www.fedlex.admin.ch/eli/cc/1995/4093_4093_4093/de', stand: '2026-06-01' },
  { key: 'ZSTV', ebene: 'bund', kuerzel: 'ZStV', titel: 'Zivilstandsverordnung vom 28. April 2004 (ZStV)', sr: '211.112.2', rechtsgebiet: 'privat', sprache: 'de', rang: 90, status: 'nur-live-link', quelleUrl: 'https://www.fedlex.admin.ch/eli/cc/2004/362/de', stand: '2025-06-01' },
  { key: 'EMRK', ebene: 'bund', kuerzel: 'EMRK', titel: 'Konvention vom 4. November 1950 zum Schutze der Menschenrechte und Grundfreiheiten (EMRK)', sr: '0.101', rechtsgebiet: 'international', sprache: 'de', rang: 90, status: 'nur-live-link', quelleUrl: 'https://www.fedlex.admin.ch/eli/cc/1974/2151_2151_2151/de', stand: '2022-09-16' },
  { key: 'CISG', ebene: 'bund', kuerzel: 'CISG', titel: 'Übereinkommen der Vereinten Nationen vom 11. April 1980 über Verträge über den internationalen Warenkauf', sr: '0.221.211.1', rechtsgebiet: 'international', sprache: 'de', rang: 90, status: 'nur-live-link', quelleUrl: 'https://www.fedlex.admin.ch/eli/cc/1991/307_307_307/de', stand: '2026-05-22' },
  { key: 'LUGUE', ebene: 'bund', kuerzel: 'LugÜ', titel: 'Übereinkommen vom 30. Oktober 2007 über die gerichtliche Zuständigkeit und die Anerkennung und Vollstreckung von Entscheidungen in Zivil- und Handelssachen (Lugano-Übereinkommen, LugÜ) (mit Prot. und Anhängen)', sr: '0.275.12', rechtsgebiet: 'international', sprache: 'de', rang: 90, status: 'nur-live-link', quelleUrl: 'https://www.fedlex.admin.ch/eli/cc/2010/801/de', stand: '2016-04-08' },
  { key: 'HZUE', ebene: 'bund', kuerzel: 'HZÜ', titel: 'Übereinkommen vom 15. November 1965 über die Zustellung gerichtlicher und aussergerichtlicher Schriftstücke im Ausland in Zivil- oder Handelssachen (mit Anhang)', sr: '0.274.131', rechtsgebiet: 'international', sprache: 'de', rang: 90, status: 'nur-live-link', quelleUrl: 'https://www.fedlex.admin.ch/eli/cc/1994/2809_2809_2809/de', stand: '2023-06-12' },
  { key: 'HBEWUE', ebene: 'bund', kuerzel: 'HBewÜ', titel: 'Übereinkommen vom 18. März 1970 über die Beweisaufnahme im Ausland in Zivil- oder Handelssachen', sr: '0.274.132', rechtsgebiet: 'international', sprache: 'de', rang: 90, status: 'nur-live-link', quelleUrl: 'https://www.fedlex.admin.ch/eli/cc/1994/2824_2824_2824/de', stand: '2026-01-01' },
  { key: 'HKUE', ebene: 'bund', kuerzel: 'HKÜ', titel: 'Übereinkommen vom 25. Oktober 1980 über die zivilrechtlichen Aspekte internationaler Kindesentführung (mit Beilage und Verzeichnis)', sr: '0.211.230.02', rechtsgebiet: 'international', sprache: 'de', rang: 90, status: 'nur-live-link', quelleUrl: 'https://www.fedlex.admin.ch/eli/cc/1983/1694_1694_1694/de', stand: '2024-06-13' },
  { key: 'FZA', ebene: 'bund', kuerzel: 'FZA', titel: 'Abkommen vom 21. Juni 1999 zwischen der Schweizerischen Eidgenossenschaft einerseits und der Europäischen Gemeinschaft und ihren Mitgliedstaaten andererseits über die Freizügigkeit (mit Anhängen, Prot. und Schlussakte)', sr: '0.142.112.681', rechtsgebiet: 'international', sprache: 'de', rang: 90, status: 'nur-live-link', quelleUrl: 'https://www.fedlex.admin.ch/eli/cc/2002/243/de', stand: '2020-12-15' },
  { key: 'VRK', ebene: 'bund', kuerzel: 'VRK', titel: 'Wiener Übereinkommen vom 23. Mai 1969 über das Recht der Verträge (mit Anhang)', sr: '0.111', rechtsgebiet: 'international', sprache: 'de', rang: 90, status: 'nur-live-link', quelleUrl: 'https://www.fedlex.admin.ch/eli/cc/1990/1112_1112_1112/de', stand: '2020-05-08' },
  { key: 'UNO_PAKT_II', ebene: 'bund', kuerzel: 'UNO-Pakt II', titel: 'Internationaler Pakt vom 16. Dezember 1966 über bürgerliche und politische Rechte', sr: '0.103.2', rechtsgebiet: 'international', sprache: 'de', rang: 90, status: 'nur-live-link', quelleUrl: 'https://www.fedlex.admin.ch/eli/cc/1993/750_750_750/de', stand: '2022-05-09' },
];
